### ISSUE TITLE
list of possible states

### ISSUE THREAD

**Issue by cesarmarinhorj** [amatsuda/stateful_enum#38]
hi, thanks! amazing plugin!
8)
I did something like:
enum status: [ :unassigned, :assigned, :resolved, :unresolved, :closed ] do
...

def status_handler
	valids = []
		
	if self.can_assign? 
		valids << ["assign", 1] 
	end
	if self.can_resolve? 
		valids << ["resolve" , 2]
	end
	if self.can_unresolve? 
		valids << ["unresolve" , 3]
	end
	if self.can_close? 
		valids << ["close" , 4]
	end
	
	valids
end

there is a better way?
thanks!

**Comment by yewness** [comment]
Check out this [video](https://www.youtube.com/watch?v=YtB4kuFlCcI&t=497s)

It details out how to use the gem through triggering a new attribute. This is a great gem but it is under-represented due to lack of documentation on how to use it.

**Comment by amatsuda** [comment]
@cesarmarinhorj Just added a simple inspection feature that returns the list of possible events and states.
Documentation: https://github.com/amatsuda/stateful_enum#inspecting-all-defined-events-and-current-possible-events
Tests: https://github.com/amatsuda/stateful_enum/blob/master/test/state_inspection_test.rb

Would this work for you? Feedbacks are welcome!

**Comment by DonSchado** [comment]
Hey @amatsuda! :) 
For me this works like a charm and I'm using the master branch in production. 👍 

So from my point of view this is ready for a release.
:shipit:

**Comment by amatsuda** [comment]
@DonSchado Thank you for your feedback, and I'm so sorry that I wasn't able to come back here sooner.
Just published a new gem versioned 0.6.0 with this feature so you can bundle a released package.
Thank you!! 😉
