### ISSUE TITLE
BUG: Support STI and inheritance

### ISSUE THREAD

**Issue by zerobearing2** [amatsuda/stateful_enum#47]
@amatsuda any chance you would merge PR to support STI & inheritance? Seems like this PR might solve the issue: https://github.com/amatsuda/stateful_enum/pull/34

**Comment by zerobearing2** [comment]
Closing issue. We're migrating to AASM instead. Would have loved to make this work _(way less bloat)_, but kept running into too many issues with inheritance, STI, and module includes with how our codebase works.

**Comment by fermion** [comment]
I just hit this issue as well. I love how simple this library is and love that it's building off of a core Rails feature.

@amatsuda I haven't looked too deeply into why this isn't working out of the box. Do you by any chance have any pointers that could help me understand the effort to get this working with Rails STI on a `User` model? 🙇🏻
